SELECT
	LOWER(TABLE_NAME) [cdm_table],
	LOWER(COLUMN_NAME) [column_name],
	UPPER(DATA_TYPE) [data_type]
FROM
	INFORMATION_SCHEMA.COLUMNS
WHERE
	TABLE_SCHEMA = 'CDM'
	AND
	TABLE_NAME NOT IN ('CDM_SOURCE', 'COMPLEX_LINKAGE', 'FINAL_AKI', 'ICU_ERA', 'METADATA')


SELECT DISTINCT variable_name
FROM
	IC3_Variable_Lookup_Table_v2_beta
