name: AI
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10.11
  - spyder=5.4.3
  - pandas=1.5.3
  - tqdm=4.65.0
  - unidecode=1.3.6
  - dask=2023.3.2
  - sqlalchemy=1.4.39
  - h5py=3.9.0
  - cryptography=41.0.1
  - scipy=1.10.1
  - openpyxl=3.1.2
  - scikit-learn=1.2.2
  - pyodbc=4.0.39
  - python-dotenv=1.0.0
  - pymysql=1.1.0
  - pytables=3.8.0
  - xlsxwriter=3.1.2
